name:                graphql-subscriptions-ws
version:             0.1.0.0
github:              "RichardWarfield/graphql-subscriptions-ws"
license:             BSD3
author:              "Richard Warfield"
maintainer:          "richard@litx.io"
copyright:           "2018 Richard Warfield"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RichardWarfield/graphql-subscriptions-ws#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- graphql-api
- microlens
- microlens-aeson
- time
- stm
- stm-containers
- async
- unagi-chan
- containers
- unordered-containers
- attoparsec
- websockets
- monad-loops

default-extensions:
- OverloadedStrings
- RankNTypes
- DataKinds
- FlexibleInstances
- FlexibleContexts
- TypeFamilies
- DeriveGeneric
- TypeApplications
- ScopedTypeVariables
- TypeOperators
- KindSignatures
- MultiParamTypeClasses
- RecordWildCards

executables:
  graphql-subscriptions-ws:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphql-subscriptions-ws

library:
  source-dirs: src

tests:
  graphql-subscriptions-ws-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphql-subscriptions-ws
